version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.11
    working_directory: ~/wayscript-python
    steps:
      - checkout
      - run:
          name: test
          command: docker-compose run --rm app test
